Configuration:
  type: object
  properties:
    workflows_path:
      description: The path to the directory containing the workflows
      type: string
      default: ./data/workflow
    templates_path:
      description: The path to the directory containing the workflow templates
      type: string
      default: ./data/templates
    db_path:
      description: The path to the WALKOFF database
      type: string
      default: ./data/walkoff.db
    case_db_path:
      description: The path to the Case database
      type: string
      default: ./data/events.db
    default_appdevice_json:
      description: Default path to imported/exported apps and devices
      type: string
      default: ./data/appdevice.json
    default_case_json:
      description: Default path to imported/exported case subscriptions
      type: string
      default: ./data/cases.json
    notifications:
      type: boolean
      default: true
    https:
      type: boolean
      default: false
    tls_version:
      type: number
      enum: [1.1, 1.2]
      default: 1.2
    host:
      type: string
      example: 127.0.1.1
      default: 127.0.1.1
    port:
      type: number
      example: 5255
      default: 5000
    walkoff_db_type:
      type: string
      example: mysql
      default: sqlite
    case_db_type:
      type: string
      example: postgresql
      default: sqlite
    num_threads:
      type: integer
      default: 5
