/configuration:
  get:
    tags:
      - Configuration
    summary: Read a configuration key
    description: ''
    operationId: server.endpoints.configuration.read_config_values
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          $ref: '#/definitions/Configuration'
  post:
    tags:
      - Configuration
    summary: Update a configuration value
    description: ''
    operationId: server.endpoints.configuration.update_configuration
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: filename
        description: name of the file to import
        required: true
        schema:
          $ref: '#/definitions/Configuration'
    responses:
      200:
        description: Success
      211:
        description: Some invalid configuration parameters were found.
/configuration/export:
  post:
    tags:
      - Cases
    summary: Export case data
    description: ''
    operationId: server.endpoints.configuration.export_config
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: filename
        description: name of the file to import
        required: false
        schema:
          required: [filename]
          properties:
            filename:
              description: Name of the file containing the JSON to import
              type: string
              default: walkoff.config
              example: walkoff_alternate.config
    responses:
      200:
        description: Success
      515:
        description: Could not write to file.
        schema:
          $ref: '#/definitions/Error'